// 全Action一覧
import { createTypes } from 'reduxsauce';

export default createTypes(`
  STARTUP

  INPUT_LEFT_CHANGE
  INPUT_RIGHT_CHANGE
  INPUT_LANGUAGE_CHANGE
  INPUT_THEME_CHANGE

  OUTPUT_DIFF_RESULT
  OUTPUT_FORMAT_CHANGE
  OUTPUT_SPLIT_CHANGE
`);
