// flow-typed signature: 989275c91c387d5465812d79b586a0b7
// flow-typed version: <<STUB>>/reactotron-redux-saga_v^1.7.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactotron-redux-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactotron-redux-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactotron-redux-saga/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactotron-redux-saga/dist/index.js' {
  declare module.exports: $Exports<'reactotron-redux-saga/dist/index'>;
}
