// flow-typed signature: 50341abb7187e84a1cd136cc4a45ea02
// flow-typed version: <<STUB>>/react-ace_v^4.1.5/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-ace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-ace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-ace/dist/react-ace' {
  declare module.exports: any;
}

declare module 'react-ace/dist/react-ace.min' {
  declare module.exports: any;
}

declare module 'react-ace/lib/ace' {
  declare module.exports: any;
}

declare module 'react-ace/src/ace' {
  declare module.exports: any;
}

declare module 'react-ace/tests/setup' {
  declare module.exports: any;
}

declare module 'react-ace/tests/src/ace.spec' {
  declare module.exports: any;
}

declare module 'react-ace/webpack.config.base' {
  declare module.exports: any;
}

declare module 'react-ace/webpack.config.development' {
  declare module.exports: any;
}

declare module 'react-ace/webpack.config.production' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-ace/dist/react-ace.js' {
  declare module.exports: $Exports<'react-ace/dist/react-ace'>;
}
declare module 'react-ace/dist/react-ace.min.js' {
  declare module.exports: $Exports<'react-ace/dist/react-ace.min'>;
}
declare module 'react-ace/lib/ace.js' {
  declare module.exports: $Exports<'react-ace/lib/ace'>;
}
declare module 'react-ace/src/ace.jsx' {
  declare module.exports: $Exports<'react-ace/src/ace'>;
}
declare module 'react-ace/tests/setup.js' {
  declare module.exports: $Exports<'react-ace/tests/setup'>;
}
declare module 'react-ace/tests/src/ace.spec.js' {
  declare module.exports: $Exports<'react-ace/tests/src/ace.spec'>;
}
declare module 'react-ace/webpack.config.base.js' {
  declare module.exports: $Exports<'react-ace/webpack.config.base'>;
}
declare module 'react-ace/webpack.config.development.js' {
  declare module.exports: $Exports<'react-ace/webpack.config.development'>;
}
declare module 'react-ace/webpack.config.production.js' {
  declare module.exports: $Exports<'react-ace/webpack.config.production'>;
}
