// flow-typed signature: f8fc7eb7ed6829dd12c39bc1d7cdc294
// flow-typed version: <<STUB>>/reduxsauce_v^0.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reduxsauce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reduxsauce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reduxsauce/dist/reduxsauce' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reduxsauce/dist/reduxsauce.js' {
  declare module.exports: $Exports<'reduxsauce/dist/reduxsauce'>;
}
