// flow-typed signature: 898de22f1975a63f7bc89c7895d0bf13
// flow-typed version: <<STUB>>/webpack-merge_v^0.15.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-merge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-merge/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-merge/src/index' {
  declare module.exports: any;
}

declare module 'webpack-merge/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-merge/lib/index.js' {
  declare module.exports: $Exports<'webpack-merge/lib/index'>;
}
declare module 'webpack-merge/src/index.js' {
  declare module.exports: $Exports<'webpack-merge/src/index'>;
}
declare module 'webpack-merge/test.js' {
  declare module.exports: $Exports<'webpack-merge/test'>;
}
